# coding: utf-8

"""
    Patient Engagement Enterprise API

    Patient Engagement Enterprise API allows multiple communication channels (e.g. websites,  HUbs, etc.) to enrroll and/or manage patient's support porgrams and services offered by Boehringer Ingelheim brands.  

    The version of the OpenAPI document: 0.7.1
    Contact: zzITEDPPatientEngagementIntegration@boehringer-ingelheim.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AddressOptional(BaseModel):
    """
    Prospect (Non-Patient) contact location for mailing or events.
    """ # noqa: E501
    address_line1: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default='874 Massachusetts Avenue', description="Street Name and number", alias="addressLine1")
    address_line2: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default=None, description="additional address information", alias="addressLine2")
    city: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default=None, description="City or town")
    state_or_province_code: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=3)]] = Field(default=None, description="State or Province of residency. Refer to brand documentation and ISO 3166 for the country of engagement. ", alias="stateOrProvinceCode")
    country_code: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2)]] = Field(default=None, description="Country of residency. Code list as defined in ISO 3166-1 alpha-2 codes.", alias="countryCode")
    postal_code: Annotated[str, Field(min_length=3, strict=True, max_length=10)] = Field(description="Address postal code. Refer to the brand documentation for more format details.", alias="postalCode")
    __properties: ClassVar[List[str]] = ["addressLine1", "addressLine2", "city", "stateOrProvinceCode", "countryCode", "postalCode"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddressOptional from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AddressOptional from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addressLine1": obj.get("addressLine1") if obj.get("addressLine1") is not None else '874 Massachusetts Avenue',
            "addressLine2": obj.get("addressLine2"),
            "city": obj.get("city"),
            "stateOrProvinceCode": obj.get("stateOrProvinceCode"),
            "countryCode": obj.get("countryCode"),
            "postalCode": obj.get("postalCode")
        })
        return _obj


