# coding: utf-8

"""
    Patient Engagement Enterprise API

    Patient Engagement Enterprise API allows multiple communication channels (e.g. websites,  HUbs, etc.) to enrroll and/or manage patient's support porgrams and services offered by Boehringer Ingelheim brands.  

    The version of the OpenAPI document: 0.7.1
    Contact: zzITEDPPatientEngagementIntegration@boehringer-ingelheim.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.clinical_details import ClinicalDetails
from openapi_server.models.clinical_education_training import ClinicalEducationTraining
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ClinicalEducationInteraction(BaseModel):
    """
    Data captured during the Clinical Educator sessions(also referred as Nurse Education)
    """ # noqa: E501
    patient_id: Optional[StrictStr] = Field(default=None, alias="patientId")
    training_status: Optional[StrictStr] = Field(default=None, alias="trainingStatus")
    education_package_shipped_date: Optional[date] = Field(default=None, alias="educationPackageShippedDate")
    classes: Optional[Annotated[List[ClinicalEducationTraining], Field(min_length=1, max_length=50)]] = None
    clinical_details: Optional[ClinicalDetails] = Field(default=None, alias="clinicalDetails")
    __properties: ClassVar[List[str]] = ["patientId", "trainingStatus", "educationPackageShippedDate", "classes", "clinicalDetails"]

    @field_validator('training_status')
    def training_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('active', 'complete', 'paused', 'unableToContact', 'optOut',):
            raise ValueError("must be one of enum values ('active', 'complete', 'paused', 'unableToContact', 'optOut')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ClinicalEducationInteraction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in classes (list)
        _items = []
        if self.classes:
            for _item in self.classes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['classes'] = _items
        # override the default output from pydantic by calling `to_dict()` of clinical_details
        if self.clinical_details:
            _dict['clinicalDetails'] = self.clinical_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ClinicalEducationInteraction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "patientId": obj.get("patientId"),
            "trainingStatus": obj.get("trainingStatus"),
            "educationPackageShippedDate": obj.get("educationPackageShippedDate"),
            "classes": [ClinicalEducationTraining.from_dict(_item) for _item in obj.get("classes")] if obj.get("classes") is not None else None,
            "clinicalDetails": ClinicalDetails.from_dict(obj.get("clinicalDetails")) if obj.get("clinicalDetails") is not None else None
        })
        return _obj


