# coding: utf-8

"""
    Patient Engagement Enterprise API

    Patient Engagement Enterprise API allows multiple communication channels (e.g. websites,  HUbs, etc.) to enrroll and/or manage patient's support porgrams and services offered by Boehringer Ingelheim brands.  

    The version of the OpenAPI document: 0.7.1
    Contact: zzITEDPPatientEngagementIntegration@boehringer-ingelheim.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CopayService(BaseModel):
    """
    Contains the information related to the Copay Insurance Card.  A Copay or copayment service card covers part of the medication cost. 
    """ # noqa: E501
    service_type: StrictStr = Field(description="Brand specific service offered by BI that would help the patient throughout their treatment journey.", alias="serviceType")
    subscription_status: StrictStr = Field(description="Latest status of the service Subscription.", alias="subscriptionStatus")
    subscription_date: Optional[date] = Field(default=None, description="Indicates the latest subcription status date change, e.g. the last date when the patient optIn or optOut from the service", alias="subscriptionDate")
    registration_system_mode: Optional[StrictStr] = Field(default=None, description="Used only when the subscription status is **registrationRequest**.    Indicates how to complete the registration process:  - **realTimeToCopayProvider**: contact the copay provider and return the card number in real time.  - **copayProvider** : offline registration process to the copay provider.  - **patientHub**: the patient hub will contact the copay provider to initiate the registration. ", alias="registrationSystemMode")
    rx_member_id: Annotated[str, Field(min_length=0, strict=True, max_length=50)] = Field(description="Patient's Prescription Insurance Assigned Membership (card) identification.    Use to return the new Copay Card Number if the request is being processed in real time.", alias="rxMemberId")
    copay_card_status: Optional[StrictStr] = Field(default=None, description="Copay membership status. This status depends on the patient eligibity. For example a patient might have opted in to copay but it their insurance changes it might not longer be eligible and the copay card will be deactivated. ", alias="copayCardStatus")
    __properties: ClassVar[List[str]] = ["serviceType", "subscriptionStatus", "subscriptionDate", "registrationSystemMode", "rxMemberId", "copayCardStatus"]

    @field_validator('service_type')
    def service_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('copay',):
            raise ValueError("must be one of enum values ('copay')")
        return value

    @field_validator('subscription_status')
    def subscription_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('registrationRequest', 'registrationPending', 'registrationFailed', 'registrationCompleted',):
            raise ValueError("must be one of enum values ('registrationRequest', 'registrationPending', 'registrationFailed', 'registrationCompleted')")
        return value

    @field_validator('registration_system_mode')
    def registration_system_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('realTimeToCopayProvider', 'copayProvider', 'patientHub',):
            raise ValueError("must be one of enum values ('realTimeToCopayProvider', 'copayProvider', 'patientHub')")
        return value

    @field_validator('copay_card_status')
    def copay_card_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('activated', 'deactivated',):
            raise ValueError("must be one of enum values ('activated', 'deactivated')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CopayService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CopayService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "serviceType": obj.get("serviceType"),
            "subscriptionStatus": obj.get("subscriptionStatus"),
            "subscriptionDate": obj.get("subscriptionDate"),
            "registrationSystemMode": obj.get("registrationSystemMode"),
            "rxMemberId": obj.get("rxMemberId"),
            "copayCardStatus": obj.get("copayCardStatus")
        })
        return _obj


