# coding: utf-8

"""
    Patient Engagement Enterprise API

    Patient Engagement Enterprise API allows multiple communication channels (e.g. websites,  HUbs, etc.) to enrroll and/or manage patient's support porgrams and services offered by Boehringer Ingelheim brands.  

    The version of the OpenAPI document: 0.7.1
    Contact: zzITEDPPatientEngagementIntegration@boehringer-ingelheim.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_server.models.consents_update_event import ConsentsUpdateEvent
from openapi_server.models.demographic_delete_event import DemographicDeleteEvent
from openapi_server.models.demographic_merge_event import DemographicMergeEvent
from openapi_server.models.demographic_un_merge_event import DemographicUnMergeEvent
from openapi_server.models.demographic_update_event import DemographicUpdateEvent
from openapi_server.models.enrollment_event import EnrollmentEvent
from openapi_server.models.pace_update_event import PaceUpdateEvent
from openapi_server.models.supply_fulfillment_event import SupplyFulfillmentEvent
from openapi_server.models.supply_order_event import SupplyOrderEvent
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

FAILEDEVENTALLOFEVENT_ANY_OF_SCHEMAS = ["ConsentsUpdateEvent", "DemographicDeleteEvent", "DemographicMergeEvent", "DemographicUnMergeEvent", "DemographicUpdateEvent", "EnrollmentEvent", "PaceUpdateEvent", "SupplyFulfillmentEvent", "SupplyOrderEvent"]

class FailedEventAllOfEvent(BaseModel):
    """
    The original event received.
    """

    # data type: EnrollmentEvent
    anyof_schema_1_validator: Optional[EnrollmentEvent] = None
    # data type: ConsentsUpdateEvent
    anyof_schema_2_validator: Optional[ConsentsUpdateEvent] = None
    # data type: DemographicUpdateEvent
    anyof_schema_3_validator: Optional[DemographicUpdateEvent] = None
    # data type: DemographicDeleteEvent
    anyof_schema_4_validator: Optional[DemographicDeleteEvent] = None
    # data type: DemographicMergeEvent
    anyof_schema_5_validator: Optional[DemographicMergeEvent] = None
    # data type: DemographicUnMergeEvent
    anyof_schema_6_validator: Optional[DemographicUnMergeEvent] = None
    # data type: SupplyOrderEvent
    anyof_schema_7_validator: Optional[SupplyOrderEvent] = None
    # data type: SupplyFulfillmentEvent
    anyof_schema_8_validator: Optional[SupplyFulfillmentEvent] = None
    # data type: PaceUpdateEvent
    anyof_schema_9_validator: Optional[PaceUpdateEvent] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ConsentsUpdateEvent, DemographicDeleteEvent, DemographicMergeEvent, DemographicUnMergeEvent, DemographicUpdateEvent, EnrollmentEvent, PaceUpdateEvent, SupplyFulfillmentEvent, SupplyOrderEvent]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: List[str] = Literal[FAILEDEVENTALLOFEVENT_ANY_OF_SCHEMAS]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = FailedEventAllOfEvent.model_construct()
        error_messages = []
        # validate data type: EnrollmentEvent
        if not isinstance(v, EnrollmentEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnrollmentEvent`")
        else:
            return v

        # validate data type: ConsentsUpdateEvent
        if not isinstance(v, ConsentsUpdateEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConsentsUpdateEvent`")
        else:
            return v

        # validate data type: DemographicUpdateEvent
        if not isinstance(v, DemographicUpdateEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DemographicUpdateEvent`")
        else:
            return v

        # validate data type: DemographicDeleteEvent
        if not isinstance(v, DemographicDeleteEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DemographicDeleteEvent`")
        else:
            return v

        # validate data type: DemographicMergeEvent
        if not isinstance(v, DemographicMergeEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DemographicMergeEvent`")
        else:
            return v

        # validate data type: DemographicUnMergeEvent
        if not isinstance(v, DemographicUnMergeEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DemographicUnMergeEvent`")
        else:
            return v

        # validate data type: SupplyOrderEvent
        if not isinstance(v, SupplyOrderEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SupplyOrderEvent`")
        else:
            return v

        # validate data type: SupplyFulfillmentEvent
        if not isinstance(v, SupplyFulfillmentEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SupplyFulfillmentEvent`")
        else:
            return v

        # validate data type: PaceUpdateEvent
        if not isinstance(v, PaceUpdateEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PaceUpdateEvent`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in FailedEventAllOfEvent with anyOf schemas: ConsentsUpdateEvent, DemographicDeleteEvent, DemographicMergeEvent, DemographicUnMergeEvent, DemographicUpdateEvent, EnrollmentEvent, PaceUpdateEvent, SupplyFulfillmentEvent, SupplyOrderEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[EnrollmentEvent] = None
        try:
            instance.actual_instance = EnrollmentEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ConsentsUpdateEvent] = None
        try:
            instance.actual_instance = ConsentsUpdateEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[DemographicUpdateEvent] = None
        try:
            instance.actual_instance = DemographicUpdateEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[DemographicDeleteEvent] = None
        try:
            instance.actual_instance = DemographicDeleteEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[DemographicMergeEvent] = None
        try:
            instance.actual_instance = DemographicMergeEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[DemographicUnMergeEvent] = None
        try:
            instance.actual_instance = DemographicUnMergeEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[SupplyOrderEvent] = None
        try:
            instance.actual_instance = SupplyOrderEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_8_validator: Optional[SupplyFulfillmentEvent] = None
        try:
            instance.actual_instance = SupplyFulfillmentEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_9_validator: Optional[PaceUpdateEvent] = None
        try:
            instance.actual_instance = PaceUpdateEvent.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FailedEventAllOfEvent with anyOf schemas: ConsentsUpdateEvent, DemographicDeleteEvent, DemographicMergeEvent, DemographicUnMergeEvent, DemographicUpdateEvent, EnrollmentEvent, PaceUpdateEvent, SupplyFulfillmentEvent, SupplyOrderEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


