# coding: utf-8

"""
    Patient Engagement Enterprise API

    Patient Engagement Enterprise API allows multiple communication channels (e.g. websites,  HUbs, etc.) to enrroll and/or manage patient's support porgrams and services offered by Boehringer Ingelheim brands.  

    The version of the OpenAPI document: 0.7.1
    Contact: zzITEDPPatientEngagementIntegration@boehringer-ingelheim.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_server.models.case_management_service import CaseManagementService
from openapi_server.models.copay_service import CopayService
from openapi_server.models.patient_education_service import PatientEducationService
from openapi_server.models.rx_bridge_service import RxBridgeService
from openapi_server.models.service_subscription_basic import ServiceSubscriptionBasic
from openapi_server.models.supply_service import SupplyService
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

SERVICESUBSCRIPTION_ANY_OF_SCHEMAS = ["CaseManagementService", "CopayService", "PatientEducationService", "RxBridgeService", "ServiceSubscriptionBasic", "SupplyService"]

class ServiceSubscription(BaseModel):
    """
    Main categories of services offered by BI directly or through its partners to which a patient can sign up to.    Each service (e..g Case Management) could provide additional \"service offerings\" not detailed here. 
    """

    # data type: ServiceSubscriptionBasic
    anyof_schema_1_validator: Optional[ServiceSubscriptionBasic] = None
    # data type: CaseManagementService
    anyof_schema_2_validator: Optional[CaseManagementService] = None
    # data type: SupplyService
    anyof_schema_3_validator: Optional[SupplyService] = None
    # data type: CopayService
    anyof_schema_4_validator: Optional[CopayService] = None
    # data type: PatientEducationService
    anyof_schema_5_validator: Optional[PatientEducationService] = None
    # data type: RxBridgeService
    anyof_schema_6_validator: Optional[RxBridgeService] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CaseManagementService, CopayService, PatientEducationService, RxBridgeService, ServiceSubscriptionBasic, SupplyService]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: List[str] = Literal[SERVICESUBSCRIPTION_ANY_OF_SCHEMAS]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ServiceSubscription.model_construct()
        error_messages = []
        # validate data type: ServiceSubscriptionBasic
        if not isinstance(v, ServiceSubscriptionBasic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ServiceSubscriptionBasic`")
        else:
            return v

        # validate data type: CaseManagementService
        if not isinstance(v, CaseManagementService):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CaseManagementService`")
        else:
            return v

        # validate data type: SupplyService
        if not isinstance(v, SupplyService):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SupplyService`")
        else:
            return v

        # validate data type: CopayService
        if not isinstance(v, CopayService):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CopayService`")
        else:
            return v

        # validate data type: PatientEducationService
        if not isinstance(v, PatientEducationService):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PatientEducationService`")
        else:
            return v

        # validate data type: RxBridgeService
        if not isinstance(v, RxBridgeService):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RxBridgeService`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ServiceSubscription with anyOf schemas: CaseManagementService, CopayService, PatientEducationService, RxBridgeService, ServiceSubscriptionBasic, SupplyService. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ServiceSubscriptionBasic] = None
        try:
            instance.actual_instance = ServiceSubscriptionBasic.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[CaseManagementService] = None
        try:
            instance.actual_instance = CaseManagementService.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[SupplyService] = None
        try:
            instance.actual_instance = SupplyService.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[CopayService] = None
        try:
            instance.actual_instance = CopayService.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[PatientEducationService] = None
        try:
            instance.actual_instance = PatientEducationService.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[RxBridgeService] = None
        try:
            instance.actual_instance = RxBridgeService.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ServiceSubscription with anyOf schemas: CaseManagementService, CopayService, PatientEducationService, RxBridgeService, ServiceSubscriptionBasic, SupplyService. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


