# coding: utf-8

"""
    Patient Engagement Enterprise API

    Patient Engagement Enterprise API allows multiple communication channels (e.g. websites,  HUbs, etc.) to enrroll and/or manage patient's support porgrams and services offered by Boehringer Ingelheim brands.  

    The version of the OpenAPI document: 0.7.1
    Contact: zzITEDPPatientEngagementIntegration@boehringer-ingelheim.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SupplyService(BaseModel):
    """
    Patient service offered by BI such as Sharps Containers and Travel Cold Case  that requires a fullfillment order to one or more parners and a delivery to the patient. 
    """ # noqa: E501
    service_type: StrictStr = Field(description="Brand specific service offered by BI that would help the patient throughout their treatment journey.", alias="serviceType")
    subscription_status: Optional[StrictStr] = Field(default=None, description="Latest status of the service Subscription. ", alias="subscriptionStatus")
    subscription_date: Optional[date] = Field(default=None, description="Indicates the latest subcription status date change, e.g. the last date when the patient optIn or optOut from the service", alias="subscriptionDate")
    fulfillment_order_id: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Unique identifier to trace the supplies orders.", alias="fulfillmentOrderId")
    order_status: Optional[StrictStr] = Field(default=None, description="Supply Order status such as shipped, pending, etc.", alias="orderStatus")
    __properties: ClassVar[List[str]] = ["serviceType", "subscriptionStatus", "subscriptionDate", "fulfillmentOrderId", "orderStatus"]

    @field_validator('service_type')
    def service_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('travelColdCase', 'sharpsContainer', 'printedEducationMaterials',):
            raise ValueError("must be one of enum values ('travelColdCase', 'sharpsContainer', 'printedEducationMaterials')")
        return value

    @field_validator('subscription_status')
    def subscription_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('orderRequest', 'orderRequestFailed', 'orderPlaced',):
            raise ValueError("must be one of enum values ('orderRequest', 'orderRequestFailed', 'orderPlaced')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupplyService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SupplyService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "serviceType": obj.get("serviceType"),
            "subscriptionStatus": obj.get("subscriptionStatus"),
            "subscriptionDate": obj.get("subscriptionDate"),
            "fulfillmentOrderId": obj.get("fulfillmentOrderId"),
            "orderStatus": obj.get("orderStatus")
        })
        return _obj


